services:
  ysws-bot:
    image: nathan5471/ysws-bot:latest
    container_name: ysws-bot
    environemnt:
      - BOT_TOKEN=your_bot_token_here
      - CLIENT_ID=your_client_id_here
      - MONGODB_URL=your_mongodb_url_here
    restart: unless-stopped